### PR TITLE
adding table relating sw and doc versions

### PR DESCRIPTION
**Pull request by fariza**
Proposal to keep track of versions between 1288pyref and 1288std

### CODE REVIEW

**Comment by fariza** [comment]
Before we start merging the PRs that migrate the code for version 4 of the standard I would like to get some kind of tracking. 
Of course we are going to bump the mayor version of this package, but still we need to inform the users what version of the standard is the code trying to follow

@zhaoyutong43210 @bebuch what do you think?

**Comment by zhaoyutong43210** [comment]
I have no problem with this.

**Comment by bebuch** [comment]
@fariza How exactly do you mean? Do you want some kind of label for functions to indicate which standard version they are compatible with?

In any case, a good idea to communicate the implemented standard version. ;-)

**Comment by fariza** [comment]
@bebuch I just want a variable that we can import so you can do your own check, the same way you cal always import `__version__` we are going to be able to import `__standard_version__` so you can do your own checks.

**Review by bebuch — APPROVED** [review]

**Review by zhaoyutong43210 — APPROVED** [review]

**Review by zhaoyutong43210 — APPROVED** [review]

**Pull request merged**
