### PR TITLE
Incluse nyquist

### PR DESCRIPTION
**Pull request by louvervecken**
Make sure we also have the Nyquist frequency in the spectrogram. Up to now only the `number_of_columns // 2` samples where shown in the spectrogram but this excludes the Nyquist frequency itself.

This means we are not showing the max frequency variation in the spectrograms which are odd-even offsets and gains. (with a period of two row or columns).
The plot below shows the horizontal spectrogram of an image filled with random values with odd-even offset added and it plots both `cols // 2` samples and `cols // 2 + 1` samples.

image

The code to generate this image is:
```python
img = np.abs(np.random.random([512, 256]))
rows = img.shape[0]
cols = img.shape[1]

img[::,::2] += 1  # add some odd-even offset

# calulate the fft
img = np.asfarray(img) - np.mean(img)
fft = np.fft.fft(img, axis=1)
fft /= np.sqrt(cols)
fabs = np.real(fft * np.conjugate(fft))
r = np.mean(fabs, axis=0)

# plot both cols // 2 and cols // 2 + 1 samples
plt.figure()
plt.plot(np.linspace(0, cols//2, cols//2)/cols, r[:cols//2], label="odd-even offset / cols//2 samples")
plt.plot(np.linspace(0, cols//2+1, cols//2+1)/cols, r[:cols//2+1], '--', label="odd-even offset / cols//2+1 samples")
plt.yscale("log")
plt.grid()
plt.xlabel("prediods/pixel")
plt.ylabel("relative presence of each cycle")
plt.show()
plt.legend()
plt.show()
```

### CODE REVIEW

**Comment by bebuch** [comment]
Compare link to workaround not-yet-merged #148:

https://github.com/louvervecken/emva1288/compare/master...louvervecken:emva1288:incluse_nyquist

Just to make the review a bit simpler ;-)

@louvervecken Is this ready for review?

**Comment by louvervecken** [comment]
@bebuch The compare the handy indeed.
Yes I believe it is ready be reviewed.

**Comment by bebuch** [comment]
Remove the `print(fft)` from the test.

Expand the test with an image with 127 cols:

```python
img = np.random.random([256, 128])
img[:, ::2] += 1
fft = routines.FFT1288(img=img)
assert fft[-1] > 1
fft = routines.FFT1288(img=np.delete(img, -1, 1))
assert fft[-1] > 1
```

I want to make sure this works with a column count that is not powers of two and/or not even.

**Comment by louvervecken** [comment]
@bebuch 
I just pushed your suggested changes

**Review by bebuch — APPROVED** [review]

**Comment by fariza** [comment]
How does this match the standard document?
Remember, it's ok to be right but the document should agree with the code

Sorry for my late participation but I'm on vacation.

**Comment by louvervecken** [comment]
@fariza This is what is in the standard:

*In the spectrograms the square root of the power spectrum is displayed as a
function of the spatial frequency v/N (in units of cycles per pixel) up to v = N/2
(Nyquist frequency). It is sufficient to draw only the first part of the power spectrum
because the power spectrum has an even symmetry*

So v=N/2 but in the code we do N//2. I guess in this case we should interpret  **"up to"** as **"up to and with Nyquist frequency included"**...

**Review by fariza — APPROVED** [review]

**Comment by fariza** [comment]
@louvervecken please rebase

**Comment by louvervecken** [comment]
@fariza, I merged the conflicting file, rebasing is not really an option when you have pushed your code already right?

**Comment by bebuch** [comment]
@louvervecken In the GitHub UI there should be a button to bring your branch up to date. After that, the commits from the previous pull request should have disappeared from this pull request.

Screenshot_20220704_122102

**Comment by louvervecken** [comment]
@bebuch 
I checked both the master and nyquist branch but both times it mentions that there "are not new commits to fetch"
image

**Comment by fariza** [comment]
@louvervecken for future reference, yes it is possible to push after rebase (-f option), as you push to your fork it doesn't really affect upstream

**Pull request merged**
