### PR TITLE
remove the bit value in Dynamic range(3.1->4.0)

### PR DESCRIPTION
**Pull request by zhaoyutong43210**
EMVA1288 4.0 report doesn't need to report the Dynamic range in bits. So this pull request is to remove that outdated feature. 

Before:
Screenshot from 2022-07-25 13-52-23

After: 
Screenshot from 2022-07-25 13-52-49

### CODE REVIEW

**Review by kirchhoefer1288 — APPROVED** [review]
Looks good to me

**Comment by fariza** [comment]
@zhaoyutong43210 please rebase and also modify the table on the main readme to change master to 4.0

**Comment by zhaoyutong43210** [comment]
> @zhaoyutong43210 please rebase and also modify the table on the main readme to change master to 4.0

Done!

**Comment by fariza** [comment]
@zhaoyutong43210 please remove changes on `Readme` file

**Comment by fariza** [comment]
@zhaoyutong43210  the file  `doc/datasets/datasets_results.rst:` also contains references to `DR_bit` please make sure you check the whole repo when doing these kind of changes.
Also please run the examples and notebooks to see if you are breaking anything, I know we should have more tests but for the time being we have to do it that way

**Review by bebuch — APPROVED** [review]
Looks fine to me, couldn't find any references to `DR_bit` in the repo.

@zhaoyutong43210 For future PR's, can you configure your editor to only remove spaces at the end of lines when saving if the line has been changed? Many modern editors support this. I'm totally in favor of fixing such code smells, but when it happens alongside content changes, it makes the diffs a bit hard to read.

**Review by fariza — APPROVED** [review]

**Pull request merged**
